language: node_js
node_js:
  - 12.16.2
sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react-proj -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react-proj npm run test